### ISSUE TITLE
Meter Reading

### ISSUE THREAD

**Issue by xion2000** [lolouk44/CurrentCost_HA_CC#2]
In the days when Current Cost hosted a web service to upload the data collected using their equipment is was possible to display a meter reading for Gas & Elec (and water if you had one I think)
is it possible to extract some data then calibrate a figure to correspond with your physical meter reading.

**Comment by lolouk44** [comment]
I actually don't need to write a script for you as I had already set the correct logging level on the custom component.
All you need to do is to set your currentcost logging level to debug.
Add these lines to your configuration.yaml:
```
logger:
  default: error
  logs:
    custom_components.currentcost: debug: debug
```
then send me the logs for a few lines
Make sure you remove this quickly else your log file will fill up like crazy

**Comment by xion2000** [comment]
[home-assistant.log](https://github.com/lolouk44/CurrentCost_HA_CC/files/4425957/home-assistant.log)

**Comment by lolouk44** [comment]
Thanks.
Can you confirm for each appliance/page number:
- what device is connected
- what unit of measurement should be used (most would be watts, but devices that are not for electricity I'm not sure)
- an example of the data you'd expect to see

**Comment by xion2000** [comment]
[Current Cost Equipment Setup for Home Assistant (GitHub Post).docx](https://github.com/lolouk44/CurrentCost_HA_CC/files/4426105/Current.Cost.Equipment.Setup.for.Home.Assistant.GitHub.Post.docx)

**Comment by lolouk44** [comment]
blimey that's some setup you got there.
I think I can get that data out.
Can you try and replace the sensor.py file in [config]/custom_components/currentcost with this one and let me know if it gives you what you expect?
[sensor.zip](https://github.com/lolouk44/CurrentCost_HA_CC/files/4426318/sensor.zip)

**Comment by xion2000** [comment]
Sorry for the delay in getting back to you
I've been double checking everything as I wasn't sure if both my EnviR's were setup the same.
This is a slightly amended document.

[Current Cost Equipment Setup for Home Assistant (GitHub Post).docx](https://github.com/lolouk44/CurrentCost_HA_CC/files/4426559/Current.Cost.Equipment.Setup.for.Home.Assistant.GitHub.Post.docx)

I have 2 EnviR's in use, 1 connected to a PC and the other connected to my Pi.
The entries using IAM's (Individual Appliance Monitors) are not really important for this setup as I can do what they do with smart plugs (flashed with tasmota)

**Comment by lolouk44** [comment]
that's fine, just list the appliances that you want to monitor in HA
I see you selected all appliances between 1 and 8.
What I do need to know is whether the updated sensor.py work, especially for meters with impulse please

**Comment by xion2000** [comment]
Screen grad attached
![CurrentCost](https://user-images.githubusercontent.com/63046811/78352093-b713cf00-759f-11ea-9865-f98c6603f71b.jpg)
Looks VERY promising (I think!!)
Thanks very much, I'm sadly quite excited about this as its something I'm very interested in (I monitor energy usage & solar production closely)
I've had the Current Cost equipment in use for many years but lost some of its uses a few years ago when their website for logging the data closed down.
I have 3 different solar systems running (1 official that I get paid for - Garage Solar, 1 grid tied I don't get paid for - Shed Solar and a new DC only system - DC Solar I'm using to power 2 small computers)
I really appreciate this work you are doing as I believe its outside of my capability.

**Comment by lolouk44** [comment]
so it looks like you're listing too many appliances as 7, 8 and 9 show as `null`
I've made a small change so return only the value for imp and IPU. I'll also rename them slightly.
Suggested names:
Imp --> Impulses
IPU --> Impulses/Unit

If you can confirm, I'll send a revised version

When you say it looks promising, is there anything that's missing or incorrect?

**Comment by xion2000** [comment]
I said promising as I presume to work out if the METER figures are working correctly I'll need to manually adjust the extracted number with my actual meter reading, do you know how I can do that
Any idea why the order of the Appliances is a bit out
I'll remove a couple of entries then get back in touch but I assumed the null entry was because its the DATA side of each meter, each meter sends out 2 streams the DATA one is just an ever increasing count I think.

**Comment by xion2000** [comment]
Yes send an updated file if you believe its still required, I'm a little out of my depth here so please bear with me

**Comment by lolouk44** [comment]
ok, for the meter figures, if any adjustment needs to be made (like the temperature for example), this should be done in HA via the template sensor, as each user may need a different adjustment.
I'm only returning the data that I get from the data stream.
See if the data shows up correctly with this latest version
[sensor.zip](https://github.com/lolouk44/CurrentCost_HA_CC/files/4426827/sensor.zip)
Changes / points to check:
- Imp is now called Impulses
- IPU is now called Impulses/Unit
- Impulses and IPU values should show without the single quotes

**Comment by xion2000** [comment]
Yes I too am only returning the data from the data stream.

![CurrentCost2](https://user-images.githubusercontent.com/63046811/78361927-18906980-75b1-11ea-8b68-a4bcc19f9cfd.jpg)


![CurrentCost Elec Meter](https://user-images.githubusercontent.com/63046811/78361937-1dedb400-75b1-11ea-906e-03262797fcff.jpg)

Do I need to change anything in my configuration.yaml?

**Comment by lolouk44** [comment]
so the data shows up nicely now.
You need to start creating template_sensors, for example:
```
  - platform: template
    sensors:
      currentcost_temperature:
        entity_id: sensor.current_cost
        unit_of_measurement: '°C'
        value_template: '{{ state_attr("sensor.current_cost", "Temperature")[:-3] | float  }}'
        friendly_name: CurrentCost Temperature
      currentcost_power:
        entity_id: sensor.current_cost
        unit_of_measurement: 'W'
        value_template: '{{ state_attr("sensor.current_cost", "Appliance 0")[:-2] | int  }}'
        friendly_name: CurrentCost Power
      dehumidifier_power:
        entity_id: sensor.current_cost
        unit_of_measurement: 'W'
        value_template: '{{ state_attr("sensor.current_cost", "Appliance 2")[:-2] | int  }}'
        friendly_name: Dehumidifier Power
```
